### ISSUE TITLE
View Network

### ISSUE THREAD

**Issue by matthew-dalton** [cs130-w21/4#1]
## Epic
Viewing the network is a feature that allows a user to leverage the personal network that they have built. It allows the user to search for certain contacts and filter them based on certain criteria, such as the company a contact works for. This will allow the user to easily identify which person they have met before would be beneficial to speak with in order to meet their professional goals.

User Actions:
- A user should be able to view their network on a website. This can be done by searching the appropriate URL and logging into your account.
- A user should be able to view their network in list or grid format. This can be done by selecting the appropriate option in the "view as" drop-down menu at the top of the page.
- A user should be able to use the filter bar to refine their search. This can be done by using one of the features in the filter bar at the top of the page: text search, company name, etc.
- A user should be able to specify the order in which contacts should be displayed. This can be done by selecting the appropriate option in the "order by" drop-down menu at the top of the page.

## User Stories
- [x] Choose how to view network #3
- [x] Filter list of contacts #5
- [x] Specify order of list of contacts #6

**Comment by summerfarren** [comment]
Finished list and grid formatting, as well as rendered toggle button. TODO: connect toggle button to switching views.
