### ISSUE TITLE
Choose how to view network

### ISSUE THREAD

**Issue by matthew-dalton** [cs130-w21/4#3]
## User Story
As a user, I would like to be able to choose how to view my network so that I can easily see my network in some order.

## Detailed Description
...

### Task List

- [x] View in list format #19 
- [x] View in grid format #20 
- [x] Toggle button between list and grid formats #21 

## Acceptance Criteria
- [x] Given the user is on the home page, then the user should be able to control how they view their network

**Comment by summerfarren** [comment]
Finished list and grid formatting, as well as rendered toggle button. TODO: connect toggle button to switching views. All on sum-contactList branch.
