### ISSUE TITLE
Remove a Contact

### ISSUE THREAD

**Issue by kiannikzad** [cs130-w21/4#55]
## User Story
As a user, I would like to delete contacts so that I can control who is my network.

## Detailed Description
 - [x] Three dot dropdown with "Delete" option #56
 - [x] Functioning "remove contact" endpoint #57
 - [x] Bind "Delete" option to endpoint #58
 - [x] Delete contact in database #72 

## Acceptance Criteria
- Given clicking on "Delete" button, then card is removed from list
