### ISSUE TITLE
Specify Order of List of Contacts

### ISSUE THREAD

**Issue by matthew-dalton** [cs130-w21/4#6]
## User Story
As a user, I would like to specify the order of my contact list so that I can see my network in order of relevance.

## Detailed Description
Provide additional details and context.

### Task List

- [x] Sort feature for list view #22 
- [x] Sort feature for grid view #23 

## Acceptance Criteria
- [x] Given that a user can view their network, then the use should be able to specify the order in which they view their network.
