### ISSUE TITLE
Register New User

### ISSUE THREAD

**Issue by kiannikzad** [cs130-w21/4#61]
## User Story
As a user, I would like to be able to register so that I can access the site.

## Detailed Description
 - [x] Register user button on login page that opens register popup #60
 - [x] Functioning "add user" endpoint #62
 - [x] Bind register popup option to endpoint #63
 - [x] Insert userObject into database #65 

## Acceptance Criteria
- [x] Given the user presses the "Register" button, then the register popup should open
- [x] Give the user presses the "Create" button, then the user is logged in automatically
