### ISSUE TITLE
Add a Contact

### ISSUE THREAD

**Issue by matthew-dalton** [cs130-w21/4#7]
## User Story
As a user, I would like to be able to add a contact so that I can update my network as I meet new people.

## Detailed Description
...

### Task List

- [x] Render button (frontend) #15
- [x] Popup menu for adding a contact #17
- [x] Submit request to "add contact" api #18 
- [x] Process "add contact" request #16
- [x] Send "add contact" response #34 
- [x] Process "add contact" response #120 
- [x] insert contact into database #53 

## Acceptance Criteria
- [x] Given the user is on the home page , then the user should be able to add a contact to their network

**Comment by matthew-dalton** [comment]
Need to properly insert contact into list on frontend
