### ISSUE TITLE
Modify a Contact

### ISSUE THREAD

**Issue by matthew-dalton** [cs130-w21/4#8]
## User Story
As a user, I would like to be able to modify a contact so that I can update my network as real world circumstances change.

## Detailed Description
 - [x] Pencil button #106 
 - [x] Create "modify mode" #107 
 - [x] Submit request to "update contact" api #108 
 - [x] Update contact in database #54 

## Acceptance Criteria
- [x] Given the user presses the pencil button, then they should view the modify mode
- [x] Given the user presses save, then changes are saved and sent to the database
