### ISSUE TITLE
View network in website

### ISSUE THREAD

**Issue by matthew-dalton** [cs130-w21/4#9]
## User Story
As a user, I would like to view my network in a website so that access my personal network from anywhere.

## Detailed Description

In order to make the product useful, the user should be able to access it via a website. This would allow the user to interact with their network from anywhere they have access to a computer and internet connection. In order for this to be possible, the scaffolding for the project must be laid down. That is, we must setup the frontend, the backend, and the continuous integration software.

### Task List
- [x] React boiler plate setup #10 
- [x] Mongo.db boiler plate setup #11 
- [x] Node.js boiler plate setup #13 
- [x] Travis CI setup #12 
- [x] Integrate boiler plate code #24

## Acceptance Criteria
...
